### PR TITLE
Finished task ( I hope 

### PR DESCRIPTION
**Pull request by Chengjing-314**
[Video link](https://youtu.be/mQczBeDvItw), [Bag link](https://drive.google.com/drive/folders/1bccTxsX8wyc-rgIlhhARhs9e-IoVTgT7?usp=sharing), please let me know if I need to make any changes, and thank you for your time!

### CODE REVIEW

**Review by sisaha9 — APPROVED** [review]
Good job

**Comment by sisaha9** [comment]
Can you share your experience with this project. What did you know before coming into this project and how did you learn the needed knowledge(what resources did you use) to complete this task

**Comment by Chengjing-314** [comment]
I had some basic knowledge of ROS before starting the project. I was taking the ROS course on The Construct for lab research purposes. I started with The Construct ROS2 course to prepare for this project, but I did not find it very helpful, since it prepares the environment for you and I was a bit lost on what they were trying to achieve so I shifted to the official doc, which appears more clearly in structure and easier to learn. Also, I glanced through some source code to learn how to structure the class, like turtlesim ( which I believe is an implementation by another user?) and joy class, and they helped a lot. Also, google is very helpful as well :)

**Comment by Chengjing-314** [comment]
Some difficulties I faced: 1. Ubuntu installation, I was running windows, ubuntu dual system desktop, but was running out of space on ubuntu and couldn't expand on the root so had to re-install ubuntu, and it took me almost a day to do so (I couldn't get enough chunk of the disk to install and had to use tools to sort that out ). 2. I have been coding a lot in python in the past year and merely wrote any c++ code, it took me some time to get used to writing in c++. 3. There are some problems that I faced that I couldn't find any answers to online, I had to figure out what was going on and resolve it (but I guess this is part of this task for 4. not an issue for me but I wonder if it may trouble others: the joystick, I had a joystick since I do play games, others may not have it and I think it could hinder them from starting the task. Thank you for your time reading this!

**Comment by sisaha9** [comment]
Since this was approved I am closing it

**Pull request closed without merging**
