### PR TITLE
Completed Onboarding Task

### PR DESCRIPTION
**Pull request by korkuteken**
[Links ](https://drive.google.com/drive/folders/1wtXWwjch_WjAuRl52KxrRmTsp0iqv3-v?usp=sharing)to the video and ros2 bag. Let me know if you have any questions or if there is a mistake!

### CODE REVIEW

**Comment by korkuteken** [comment]
Just to let you know, for some reason it didn't push .srv and .msg files and I don't really know how to fix it.

**Comment by sisaha9** [comment]
The code looks good to me. Not sure why you are not being allowed to push .msg or .srv files. Waiting for access to the GDrive link

**Comment by korkuteken** [comment]
Try now. It should work now.

**Comment by sisaha9** [comment]
Looks good to me! Can you share your experience with this project. What did you know before coming into this project and how did you learn the needed knowledge(what resources did you use) to complete this task

**Review by sisaha9 — APPROVED** [review]

**Comment by HaoruXue** [comment]
Nicely done!

**Comment by korkuteken** [comment]
I had some really basic knowledge of ROS1 subscribers/publishers from an undergrad class but I definitely needed a refresher. I just followed the tutorials provided in the ROS2 Galactic documentation for subscribers, publishers, and other necessary things to complete the task. I think they were really helpful to understand the basics. As I was using WSL to complete the task, I couldn't use my controller or at least I couldn't figure out how to so I just used the joystick bag provided. Overall, onboarding task feels like it made me learn the ropes of ROS2's basics.

**Comment by sisaha9** [comment]
Great! Yes unfortunately windows joystick mounting is something we haven't been able to get around either. Thanks for your feedback! Your task is approved

**Pull request closed without merging**
